services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: agroveterinaria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d agroveterinaria_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - red-app

  app:
    build: .
    container_name: app
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin1234
      DB_NAME: agroveterinaria_db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red-app

volumes:
  postgres_data:

networks:
  red-app:
    driver: bridge
