ALTER TABLE ruta_parada ADD COLUMN longitud DOUBLE PRECISION;
ALTER TABLE ruta_parada ADD COLUMN latitud DOUBLE PRECISION;

ALTER TABLE ruta DROP COLUMN tiempo_estimado;
ALTER TABLE ruta ADD COLUMN tiempo_estimado BIGINT NOT NULL DEFAULT 0;