-- Modelo fisico inicial para PostgreSQL.
-- Fuente: diagrama aprobado "1.2 Modelo Fisico de Datos".
-- TODO: validar contra el archivo fuente del diagrama cuando este disponible.

-- Personas, usuarios y empleados
CREATE TABLE persona (
    id_persona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL
);

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE empleado (
    id_empleado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    salario DECIMAL(12,2) NOT NULL CHECK (salario >= 0),
    CONSTRAINT fk_empleado_persona
        FOREIGN KEY (id_persona) REFERENCES persona (id_persona)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_empleado_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE empleado_rol (
    id_empleado_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado BIGINT NOT NULL,
    rol VARCHAR(30) NOT NULL CHECK (rol IN ('ADMINISTRADOR', 'CAJERO', 'VETERINARIO', 'ASISTENTE', 'CONDUCTOR')),
    CONSTRAINT uq_empleado_rol UNIQUE (id_empleado, rol),
    CONSTRAINT fk_empleado_rol_empleado
        FOREIGN KEY (id_empleado) REFERENCES empleado (id_empleado)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rnc VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVO', 'INACTIVO')),
    num_persona_contacto VARCHAR(20) NOT NULL
);

-- Clientes, mascotas y servicios
CREATE TABLE tipo_cliente (
    id_tipo_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo_cliente VARCHAR(60) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    descuento DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0 AND descuento <= 100)
);

CREATE TABLE cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona BIGINT NOT NULL,
    longitud FLOAT(53),
    latitud FLOAT(53),
    id_tipo_cliente BIGINT NOT NULL,
    CONSTRAINT uq_cliente_persona UNIQUE (id_persona),
    CONSTRAINT fk_cliente_persona
        FOREIGN KEY (id_persona) REFERENCES persona (id_persona)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_cliente_tipo_cliente
        FOREIGN KEY (id_tipo_cliente) REFERENCES tipo_cliente (id_tipo_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE mascota (
    id_mascota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    fecha_nacim DATE,
    tipo_animal VARCHAR(30) NOT NULL CHECK (tipo_animal IN ('PERRO')),
    raza VARCHAR(80),
    sexo VARCHAR(20),
    CONSTRAINT fk_mascota_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE cita (
    id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_mascota BIGINT NOT NULL,
    id_veterinario BIGINT NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    realizado BOOLEAN NOT NULL DEFAULT FALSE,
    id_servicio BIGINT NOT NULL,
    CONSTRAINT fk_cita_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_cita_mascota
        FOREIGN KEY (id_mascota) REFERENCES mascota (id_mascota)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_cita_veterinario
        FOREIGN KEY (id_veterinario) REFERENCES empleado (id_empleado)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE realizacion_servicio (
    id_realizacion_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cita BIGINT NOT NULL,
    CONSTRAINT fk_realizacion_servicio_cita
        FOREIGN KEY (id_cita) REFERENCES cita (id_cita)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Productos, lotes e inventario
CREATE TABLE producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL CHECK (precio_unitario >= 0),
    categoria VARCHAR(30) NOT NULL CHECK (categoria IN ('ALIMENTO', 'MEDICAMENTO', 'MATERIA_PRIMA', 'PRODUCTOS_VARIOS', 'SERVICIO')),
    unidad_medida VARCHAR(30) NOT NULL CHECK (unidad_medida IN ('LIBRA', 'QUINTAL', 'KILOGRAMO', 'CC', 'LITRO', 'MILILITRO', 'UNIDAD'))
);

ALTER TABLE cita
    ADD CONSTRAINT fk_cita_servicio
    FOREIGN KEY (id_servicio) REFERENCES producto (id_producto)
    ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE lote (
    id_lote BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL,
    fecha_vencimiento DATE,
    CONSTRAINT fk_lote_producto
        FOREIGN KEY (id_producto) REFERENCES producto (id_producto)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE almacen (
    id_almacen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    direccion VARCHAR(255) NOT NULL
);

CREATE TABLE inventario (
    id_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen BIGINT NOT NULL,
    id_lote BIGINT NOT NULL,
    cantidad_actual INT NOT NULL CHECK (cantidad_actual >= 0),
    CONSTRAINT uq_inventario_almacen_lote UNIQUE (id_almacen, id_lote),
    CONSTRAINT fk_inventario_almacen
        FOREIGN KEY (id_almacen) REFERENCES almacen (id_almacen)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventario_lote
        FOREIGN KEY (id_lote) REFERENCES lote (id_lote)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE transferencia (
    id_transferencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_salida_programada TIMESTAMP NOT NULL,
    fecha_hora_llegada_programada TIMESTAMP,
    id_transporte BIGINT,
    id_almacen_origen BIGINT NOT NULL,
    id_almacen_destino BIGINT NOT NULL,
    CONSTRAINT chk_transferencia_almacenes_distintos CHECK (id_almacen_origen <> id_almacen_destino),
    CONSTRAINT fk_transferencia_almacen_origen
        FOREIGN KEY (id_almacen_origen) REFERENCES almacen (id_almacen)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_transferencia_almacen_destino
        FOREIGN KEY (id_almacen_destino) REFERENCES almacen (id_almacen)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE detalle_transferencia (
    id_detalle_transferencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_transferencia BIGINT NOT NULL,
    id_lote BIGINT NOT NULL,
    cantidad BIGINT NOT NULL CHECK (cantidad > 0),
    CONSTRAINT fk_detalle_transferencia_transferencia
        FOREIGN KEY (id_transferencia) REFERENCES transferencia (id_transferencia)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_transferencia_lote
        FOREIGN KEY (id_lote) REFERENCES lote (id_lote)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Compras y pagos
CREATE TABLE gasto_operativo (
    id_gasto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_gasto VARCHAR(20) NOT NULL CHECK (tipo_gasto IN ('FIJO', 'VARIABLE')),
    fecha DATE NOT NULL,
    monto DECIMAL(12,2) NOT NULL CHECK (monto >= 0),
    comprobante_fiscal VARCHAR(50),
    notas VARCHAR(255)
);

CREATE TABLE compra (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_gasto BIGINT,
    fecha_hora_compra TIMESTAMP NOT NULL,
    id_proveedor BIGINT NOT NULL,
    total DECIMAL(12,2) NOT NULL CHECK (total >= 0),
    fecha_vencimiento_pago TIMESTAMP,
    CONSTRAINT fk_compra_gasto
        FOREIGN KEY (id_gasto) REFERENCES gasto_operativo (id_gasto)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_compra_proveedor
        FOREIGN KEY (id_proveedor) REFERENCES proveedor (id_proveedor)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE detalle_compra (
    id_detalle_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra BIGINT NOT NULL,
    id_lote BIGINT NOT NULL,
    cantidad BIGINT NOT NULL CHECK (cantidad > 0),
    precio_unitario_compra DECIMAL(12,2) NOT NULL CHECK (precio_unitario_compra >= 0),
    impuesto DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (impuesto >= 0),
    CONSTRAINT fk_detalle_compra_compra
        FOREIGN KEY (id_compra) REFERENCES compra (id_compra)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_compra_lote
        FOREIGN KEY (id_lote) REFERENCES lote (id_lote)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE pago (
    id_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    monto_total DECIMAL(12,2) NOT NULL CHECK (monto_total >= 0),
    metodo_pago VARCHAR(30) NOT NULL CHECK (metodo_pago IN ('EFECTIVO', 'TARJETA', 'NOTA_CREDITO', 'TRANSFERENCIA')),
    CONSTRAINT fk_pago_proveedor
        FOREIGN KEY (id_proveedor) REFERENCES proveedor (id_proveedor)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Ventas, cobros y devoluciones
CREATE TABLE venta (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_venta TIMESTAMP NOT NULL,
    monto_total DECIMAL(12,2) NOT NULL CHECK (monto_total >= 0),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('NEGOCIACION', 'PENDIENTE', 'CERRADA')),
    id_cliente BIGINT NOT NULL,
    id_vendedor BIGINT NOT NULL,
    comprobante_fiscal VARCHAR(50),
    aplica_descuento_venta BOOLEAN NOT NULL DEFAULT FALSE,
    lleva_despacho BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_vencimiento_pago TIMESTAMP,
    CONSTRAINT fk_venta_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_venta_vendedor
        FOREIGN KEY (id_vendedor) REFERENCES empleado (id_empleado)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE detalle_venta (
    id_detalle_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad BIGINT NOT NULL CHECK (cantidad > 0),
    precio_unitario_venta DECIMAL(12,2) NOT NULL CHECK (precio_unitario_venta >= 0),
    impuesto DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (impuesto >= 0),
    CONSTRAINT fk_detalle_venta_venta
        FOREIGN KEY (id_venta) REFERENCES venta (id_venta)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_venta_producto
        FOREIGN KEY (id_producto) REFERENCES producto (id_producto)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE cobro (
    id_cobro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    monto_total DECIMAL(12,2) NOT NULL CHECK (monto_total >= 0),
    metodo_pago VARCHAR(30) NOT NULL CHECK (metodo_pago IN ('EFECTIVO', 'TARJETA', 'NOTA_CREDITO', 'TRANSFERENCIA')),
    CONSTRAINT fk_cobro_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE nota_credito (
    id_nota_credito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    monto DECIMAL(12,2) NOT NULL CHECK (monto >= 0),
    CONSTRAINT fk_nota_credito_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE devolucion_venta (
    id_devolucion_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMP NOT NULL,
    id_cliente BIGINT NOT NULL,
    razon_devolucion VARCHAR(255) NOT NULL,
    id_empleado BIGINT NOT NULL,
    CONSTRAINT fk_devolucion_venta_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_devolucion_venta_empleado
        FOREIGN KEY (id_empleado) REFERENCES empleado (id_empleado)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE detalle_dev_venta (
    id_detalle_dev_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_devolucion_venta BIGINT NOT NULL,
    cantidad_devuelta INT NOT NULL CHECK (cantidad_devuelta > 0),
    id_detalle_venta BIGINT NOT NULL,
    id_lote BIGINT NOT NULL,
    id_almacen_entrada BIGINT NOT NULL,
    CONSTRAINT fk_detalle_dev_venta_devolucion
        FOREIGN KEY (id_devolucion_venta) REFERENCES devolucion_venta (id_devolucion_venta)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_dev_venta_detalle_venta
        FOREIGN KEY (id_detalle_venta) REFERENCES detalle_venta (id_detalle_venta)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_dev_venta_lote
        FOREIGN KEY (id_lote) REFERENCES lote (id_lote)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_dev_venta_almacen
        FOREIGN KEY (id_almacen_entrada) REFERENCES almacen (id_almacen)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Servicios y gastos asociados
CREATE TABLE gasto_realizacion_servicio (
    id_gasto_realizacion_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_gasto BIGINT NOT NULL,
    id_realizacion_servicio BIGINT NOT NULL,
    CONSTRAINT fk_gasto_realizacion_servicio_gasto
        FOREIGN KEY (id_gasto) REFERENCES gasto_operativo (id_gasto)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_gasto_realizacion_servicio_realizacion
        FOREIGN KEY (id_realizacion_servicio) REFERENCES realizacion_servicio (id_realizacion_servicio)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Transporte, despacho y recepcion
CREATE TABLE vehiculo (
    id_vehiculo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(20) NOT NULL UNIQUE,
    modelo VARCHAR(80) NOT NULL,
    capacidad_carga DECIMAL(12,2) NOT NULL CHECK (capacidad_carga >= 0)
);

CREATE TABLE ruta (
    id_ruta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distancia_km DECIMAL(12,2) NOT NULL CHECK (distancia_km >= 0),
    tiempo_estimado VARCHAR(50) NOT NULL
);

CREATE TABLE ruta_parada (
    id_ruta_parada BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ruta BIGINT NOT NULL,
    parada VARCHAR(150) NOT NULL,
    orden INT NOT NULL CHECK (orden > 0),
    CONSTRAINT uq_ruta_parada_orden UNIQUE (id_ruta, orden),
    CONSTRAINT fk_ruta_parada_ruta
        FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE transporte (
    id_transporte BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_salida TIMESTAMP,
    fecha_hora_llegada TIMESTAMP,
    id_vehiculo BIGINT NOT NULL,
    id_conductor BIGINT NOT NULL,
    id_ruta BIGINT NOT NULL,
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('PROGRAMADO', 'EN_TRANSITO', 'COMPLETADO', 'FALLIDO', 'CANCELADO')),
    descuento DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    CONSTRAINT fk_transporte_vehiculo
        FOREIGN KEY (id_vehiculo) REFERENCES vehiculo (id_vehiculo)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_transporte_conductor
        FOREIGN KEY (id_conductor) REFERENCES empleado (id_empleado)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_transporte_ruta
        FOREIGN KEY (id_ruta) REFERENCES ruta (id_ruta)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE transferencia
    ADD CONSTRAINT fk_transferencia_transporte
    FOREIGN KEY (id_transporte) REFERENCES transporte (id_transporte)
    ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE despacho (
    id_despacho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_salida_programada TIMESTAMP NOT NULL,
    id_transporte BIGINT NOT NULL,
    fecha_hora_entrega TIMESTAMP,
    CONSTRAINT fk_despacho_transporte
        FOREIGN KEY (id_transporte) REFERENCES transporte (id_transporte)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE recepcion (
    id_recepcion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_llegada_programada TIMESTAMP NOT NULL,
    id_transporte BIGINT NOT NULL,
    fecha_hora_recepcion TIMESTAMP,
    CONSTRAINT fk_recepcion_transporte
        FOREIGN KEY (id_transporte) REFERENCES transporte (id_transporte)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE detalle_despacho (
    id_detalle_despacho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_despacho BIGINT NOT NULL,
    id_detalle_venta BIGINT NOT NULL,
    id_lote BIGINT NOT NULL,
    id_almacen BIGINT NOT NULL,
    cantidad BIGINT NOT NULL CHECK (cantidad > 0),
    CONSTRAINT fk_detalle_despacho_despacho
        FOREIGN KEY (id_despacho) REFERENCES despacho (id_despacho)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_despacho_detalle_venta
        FOREIGN KEY (id_detalle_venta) REFERENCES detalle_venta (id_detalle_venta)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_despacho_lote
        FOREIGN KEY (id_lote) REFERENCES lote (id_lote)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_despacho_almacen
        FOREIGN KEY (id_almacen) REFERENCES almacen (id_almacen)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE detalle_recepcion (
    id_detalle_recepcion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recepcion BIGINT NOT NULL,
    id_detalle_compra BIGINT NOT NULL,
    cantidad BIGINT NOT NULL CHECK (cantidad > 0),
    id_almacen BIGINT NOT NULL,
    CONSTRAINT fk_detalle_recepcion_recepcion
        FOREIGN KEY (id_recepcion) REFERENCES recepcion (id_recepcion)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_recepcion_detalle_compra
        FOREIGN KEY (id_detalle_compra) REFERENCES detalle_compra (id_detalle_compra)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_recepcion_almacen
        FOREIGN KEY (id_almacen) REFERENCES almacen (id_almacen)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE recepcion_compra (
    id_recepcion BIGINT NOT NULL,
    id_compra BIGINT NOT NULL,
    PRIMARY KEY (id_recepcion, id_compra),
    CONSTRAINT fk_recepcion_compra_recepcion
        FOREIGN KEY (id_recepcion) REFERENCES recepcion (id_recepcion)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_recepcion_compra_compra
        FOREIGN KEY (id_compra) REFERENCES compra (id_compra)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE despacho_venta (
    id_despacho BIGINT NOT NULL,
    id_venta BIGINT NOT NULL,
    PRIMARY KEY (id_despacho, id_venta),
    CONSTRAINT fk_despacho_venta_despacho
        FOREIGN KEY (id_despacho) REFERENCES despacho (id_despacho)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_despacho_venta_venta
        FOREIGN KEY (id_venta) REFERENCES venta (id_venta)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE gasto_transporte (
    id_gasto_transporte BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_transporte BIGINT NOT NULL,
    id_gasto BIGINT NOT NULL,
    CONSTRAINT fk_gasto_transporte_transporte
        FOREIGN KEY (id_transporte) REFERENCES transporte (id_transporte)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_gasto_transporte_gasto
        FOREIGN KEY (id_gasto) REFERENCES gasto_operativo (id_gasto)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Contabilidad

-- Nomina
CREATE TABLE nomina (
    id_nomina BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado BIGINT NOT NULL,
    fecha_emision DATE NOT NULL,
    periodo VARCHAR(20) NOT NULL CHECK (periodo IN ('MES', 'QUINCENA')),
    total_devengado DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (total_devengado >= 0),
    total_deducciones DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (total_deducciones >= 0),
    CONSTRAINT fk_nomina_empleado
        FOREIGN KEY (id_empleado) REFERENCES empleado (id_empleado)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE detalle_nomina (
    id_detalle_nomina BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nomina BIGINT NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    tipo VARCHAR(40) NOT NULL CHECK (tipo IN (
        'SALARIO_BASE',
        'HORAS_EXTRAS',
        'COMISIONES',
        'BONIFICACIONES',
        'PAGO_VACACIONES',
        'SUELDO_13',
        'DIETAS_Y_VIATICOS',
        'SEGURO_FAMILIAR_SALUD',
        'FONDO_PENSIONES',
        'IMPUESTO_RENTA',
        'ANTICIPO_SALARIO',
        'PRESTAMO_EMPRESA',
        'AUSENCIAS_NO_PAGADAS',
        'EMBARGO_SALARIAL',
        'OTRAS_DEDUCCIONES'
    )),
    monto DECIMAL(12,2) NOT NULL CHECK (monto >= 0),
    cantidad DECIMAL(12,2) NOT NULL DEFAULT 1 CHECK (cantidad >= 0),
    CONSTRAINT fk_detalle_nomina_nomina
        FOREIGN KEY (id_nomina) REFERENCES nomina (id_nomina)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Indices para llaves foraneas y busquedas frecuentes
CREATE INDEX idx_empleado_persona ON empleado (id_persona);
CREATE INDEX idx_empleado_usuario ON empleado (id_usuario);
CREATE INDEX idx_empleado_rol_empleado ON empleado_rol (id_empleado);
CREATE INDEX idx_proveedor_status ON proveedor (status);
CREATE INDEX idx_cliente_persona ON cliente (id_persona);
CREATE INDEX idx_cliente_tipo_cliente ON cliente (id_tipo_cliente);
CREATE INDEX idx_mascota_cliente ON mascota (id_cliente);
CREATE INDEX idx_producto_categoria ON producto (categoria);
CREATE INDEX idx_producto_unidad_medida ON producto (unidad_medida);
CREATE INDEX idx_lote_producto ON lote (id_producto);
CREATE INDEX idx_inventario_almacen_lote ON inventario (id_almacen, id_lote);
CREATE INDEX idx_inventario_lote ON inventario (id_lote);
CREATE INDEX idx_compra_gasto ON compra (id_gasto);
CREATE INDEX idx_compra_proveedor ON compra (id_proveedor);
CREATE INDEX idx_detalle_compra_compra ON detalle_compra (id_compra);
CREATE INDEX idx_detalle_compra_lote ON detalle_compra (id_lote);
CREATE INDEX idx_pago_proveedor ON pago (id_proveedor);
CREATE INDEX idx_venta_cliente ON venta (id_cliente);
CREATE INDEX idx_venta_vendedor ON venta (id_vendedor);
CREATE INDEX idx_venta_estado ON venta (estado);
CREATE INDEX idx_detalle_venta_venta ON detalle_venta (id_venta);
CREATE INDEX idx_detalle_venta_producto ON detalle_venta (id_producto);
CREATE INDEX idx_cobro_cliente ON cobro (id_cliente);
CREATE INDEX idx_nota_credito_cliente ON nota_credito (id_cliente);
CREATE INDEX idx_devolucion_venta_cliente ON devolucion_venta (id_cliente);
CREATE INDEX idx_devolucion_venta_empleado ON devolucion_venta (id_empleado);
CREATE INDEX idx_detalle_dev_venta_devolucion ON detalle_dev_venta (id_devolucion_venta);
CREATE INDEX idx_detalle_dev_venta_detalle_venta ON detalle_dev_venta (id_detalle_venta);
CREATE INDEX idx_detalle_dev_venta_lote ON detalle_dev_venta (id_lote);
CREATE INDEX idx_detalle_dev_venta_almacen ON detalle_dev_venta (id_almacen_entrada);
CREATE INDEX idx_cita_cliente ON cita (id_cliente);
CREATE INDEX idx_cita_mascota ON cita (id_mascota);
CREATE INDEX idx_cita_veterinario ON cita (id_veterinario);
CREATE INDEX idx_cita_servicio ON cita (id_servicio);
CREATE INDEX idx_realizacion_servicio_cita ON realizacion_servicio (id_cita);
CREATE INDEX idx_gasto_realizacion_servicio_gasto ON gasto_realizacion_servicio (id_gasto);
CREATE INDEX idx_gasto_realizacion_servicio_realizacion ON gasto_realizacion_servicio (id_realizacion_servicio);
CREATE INDEX idx_ruta_parada_ruta ON ruta_parada (id_ruta);
CREATE INDEX idx_transporte_vehiculo ON transporte (id_vehiculo);
CREATE INDEX idx_transporte_conductor ON transporte (id_conductor);
CREATE INDEX idx_transporte_ruta ON transporte (id_ruta);
CREATE INDEX idx_transferencia_transporte ON transferencia (id_transporte);
CREATE INDEX idx_transferencia_almacen_origen ON transferencia (id_almacen_origen);
CREATE INDEX idx_transferencia_almacen_destino ON transferencia (id_almacen_destino);
CREATE INDEX idx_detalle_transferencia_transferencia ON detalle_transferencia (id_transferencia);
CREATE INDEX idx_detalle_transferencia_lote ON detalle_transferencia (id_lote);
CREATE INDEX idx_despacho_transporte ON despacho (id_transporte);
CREATE INDEX idx_recepcion_transporte ON recepcion (id_transporte);
CREATE INDEX idx_detalle_despacho_despacho ON detalle_despacho (id_despacho);
CREATE INDEX idx_detalle_despacho_detalle_venta ON detalle_despacho (id_detalle_venta);
CREATE INDEX idx_detalle_despacho_lote ON detalle_despacho (id_lote);
CREATE INDEX idx_detalle_despacho_almacen ON detalle_despacho (id_almacen);
CREATE INDEX idx_detalle_recepcion_recepcion ON detalle_recepcion (id_recepcion);
CREATE INDEX idx_detalle_recepcion_detalle_compra ON detalle_recepcion (id_detalle_compra);
CREATE INDEX idx_detalle_recepcion_almacen ON detalle_recepcion (id_almacen);
CREATE INDEX idx_gasto_transporte_transporte ON gasto_transporte (id_transporte);
CREATE INDEX idx_gasto_transporte_gasto ON gasto_transporte (id_gasto);
CREATE INDEX idx_nomina_empleado ON nomina (id_empleado);
CREATE INDEX idx_detalle_nomina_nomina ON detalle_nomina (id_nomina);
