CREATE TABLE "public"."ajuste_inventario" (
    "id_ajuste" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_almacen" bigint NOT NULL,
    "id_lote" bigint NOT NULL,
    "id_empleado" bigint NOT NULL,
    "tipo_ajuste" character varying NOT NULL,
    "cantidad" numeric NOT NULL,
    "justificacion" character varying NOT NULL,
    "fecha_hora" timestamp without time zone NOT NULL,
    CONSTRAINT "fk_ajuste_almacen" FOREIGN KEY ("id_almacen") REFERENCES "public"."almacen"("id_almacen"),
    CONSTRAINT "fk_ajuste_lote" FOREIGN KEY ("id_lote") REFERENCES "public"."lote"("id_lote"),
    CONSTRAINT "fk_ajuste_empleado" FOREIGN KEY ("id_empleado") REFERENCES "public"."empleado"("id_empleado")
);

ALTER TABLE "public"."detalle_recepcion"
    ADD COLUMN "cantidad_merma" numeric DEFAULT 0,
ADD COLUMN "justificacion_merma" character varying;