ALTER TABLE detalle_nomina DROP CONSTRAINT detalle_nomina_tipo_check;

ALTER TABLE detalle_nomina ADD CONSTRAINT detalle_nomina_tipo_check CHECK (tipo IN (
    'SALARIO_BASE',
    'HORAS_EXTRAS',
    'COMISIONES_REGULARES',
    'COMISIONES_EXTRAORDINARIAS',
    'BONIFICACIONES',
    'PAGO_VACACIONES',
    'SUELDO_13',
    'DIETAS_Y_VIATICOS',
    'REEMBOLSO_LICENCIA',

    'SEGURO_FAMILIAR_SALUD',
    'FONDO_PENSIONES',
    'IMPUESTO_RENTA',
    'ANTICIPO_SALARIO',
    'PRESTAMO_EMPRESA',
    'DESCUENTO_AUSENCIA',
    'INFOTEP',
    'EMBARGO_SALARIAL'
));